# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21bcfc0c3046709db0ee4bda91d9177677d0b03492cabf06d0e1d252b1c11f5d1de23d82b8db0591417b41f6bc9bcb32a8f0d65d674b6b1d75b2cf75b824b698

test:
  secret_key_base: 9eb96895ddac2e21cc1b1faa5fdb3990f4046f7701cdaeefc0ea2dd2c565f843bc88927ac804c6d816323ee000129c6a6f856bcd04313d0fed9dff58e874a524

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
